"""Flatten `main.py` + `kagfarm/` into one self-contained `submission/main.py`, then prove it.

Kaggle simulation harnesses differ on what they accept. Most unpack an archive and put its root
on `sys.path`, which is what `main.py` and the `kagfarm` package are built for; some want a single
file and nothing else. This produces the single file so that the choice is never a blocker on
submission day, and -- more importantly -- it verifies the flattened copy by playing it against
the mirror engine and requiring bank-for-bank agreement with the package build. A bundler that is
not diffed against its source is a silent way to submit a different agent than the one measured.

The flattening itself is mechanical because the package has no import cycles and no third-party
dependencies: `constants` (stdlib only) -> `route` -> `policy` -> entry point. Three relative
imports are dropped and the module bodies are concatenated in that order.

    python3 bundle.py            # writes submission/main.py and verifies it
    python3 bundle.py --seeds 8  # verify over more episodes
"""

from __future__ import annotations

import argparse
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

# Dependency order. Anything added to `kagfarm` has to be listed here, and the verification
# below is what catches it if it is not: a missing module is a NameError on the first turn.
MODULES = ("constants", "route", "policy")

HEADER = '''"""Kaggriculture agent -- single-file build. GENERATED by bundle.py; do not edit.

Flattened from `main.py` and the `kagfarm` package ({mods}) in dependency
order, with the relative imports dropped. The source of truth is the package; regenerate with

    python3 bundle.py

which also verifies that this file plays identically to the package build on the mirror engine.
"""

from __future__ import annotations

import math
import time
'''

# The import machinery in `main.py`, which the bundle does not need because `Policy` is already
# defined above it by then. Matched exactly rather than by regex: if `main.py` changes shape the
# replacement fails loudly instead of quietly shipping a file that cannot find its own policy.
MAIN_IMPORT_BLOCK = '''from __future__ import annotations

import os
import sys


def _locate_root():
    """Directory containing the kagfarm package, without ever touching __file__ blindly."""
    try:
        here = os.path.dirname(os.path.abspath(__file__))    # real module import context
        if os.path.isfile(os.path.join(here, "kagfarm", "policy.py")):
            return here
    except NameError:
        pass                                                  # exec'd source: no __file__
    for cand in sys.path:                                     # harness exec context
        try:
            if cand and os.path.isfile(os.path.join(cand, "kagfarm", "policy.py")):
                return cand
        except Exception:
            pass
    return os.getcwd()


_HERE = _locate_root()
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

_POLICIES = {}
_BROKEN = None


def _import_policy():
    """Import OUR kagfarm package, not a same-named one an earlier agent cached.

    The harness can run both seats in one process. If the opponent also ships a top-level
    package named `kagfarm` and their agent is built first, `sys.modules` caches theirs and
    a plain `from kagfarm.policy import Policy` would silently bind their code -- this seat
    would then PASS all episode (or worse, play their policy). So: import, check the loaded
    package actually lives in _HERE, purge and re-import if it does not (re-import only
    affects new lookups; the opponent's already-bound references are untouched).
    """
    import kagfarm
    pkg_dir = os.path.dirname(os.path.abspath(kagfarm.__file__))
    if os.path.realpath(pkg_dir) != os.path.realpath(os.path.join(_HERE, "kagfarm")):
        for name in [m for m in list(sys.modules)
                     if m == "kagfarm" or m.startswith("kagfarm.")]:
            del sys.modules[name]
        import kagfarm
    from kagfarm.policy import Policy
    return Policy


try:
    Policy = _import_policy()
except Exception as _e:                        # pragma: no cover - sandbox import failure
    Policy = None
    _BROKEN = repr(_e)
'''

MAIN_REPLACEMENT = '''# -- entry point ------------------------------------------------------------------------------
# `Policy` is defined above in this same file, so the guarded import the package build needs is
# replaced by the two names that depended on it. `Policy is None` stays reachable as a concept --
# nothing sets it now -- because the `agent` body below is copied verbatim from `main.py` and
# keeping it identical is the point of doing this by substitution rather than by rewriting.

_POLICIES = {}
_BROKEN = None
Policy = Policy
'''


def strip_module(src):
    """Module body with its own imports and relative imports removed.

    Skips parenthesised imports by counting brackets rather than looking for a trailing comma,
    because `from .constants import (...)` spans five lines and a line-at-a-time filter would
    leave the tail of the list behind as a syntax error.
    """
    out = []
    depth = 0
    for line in src.splitlines():
        if depth:
            depth += line.count("(") - line.count(")")
            continue
        if line.startswith(("from .", "from __future__", "import math", "import time")):
            depth = line.count("(") - line.count(")")
            continue
        out.append(line)
    return "\n".join(out).strip("\n")


def build():
    """Return the single-file source. Raises if `main.py` no longer matches the expected shape."""
    parts = [HEADER.format(mods=", ".join(MODULES))]
    for mod in MODULES:
        with open(os.path.join(_HERE, "kagfarm", "%s.py" % mod)) as fh:
            src = fh.read()
        parts.append("# " + "=" * 92)
        parts.append("# kagfarm/%s.py" % mod)
        parts.append("# " + "=" * 92 + "\n")
        parts.append(strip_module(src) + "\n")
    with open(os.path.join(_HERE, "main.py")) as fh:
        main_src = fh.read()
    if MAIN_IMPORT_BLOCK not in main_src:
        raise SystemExit("bundle.py: main.py's import block has changed shape -- update "
                         "MAIN_IMPORT_BLOCK to match before regenerating the bundle.")
    # 0930c-sub24: embed the elite opening book into the single-file build. The package
    # build reads kagfarm/opening_book_elite.json from beside policy.py (pack.sh ships
    # it); the flattened file has no package directory, so without the embedding the
    # bundle would silently play book-off and bank-for-bank verification would compare
    # two different agents. Optional by design: a missing file just ships planner-only.
    replacement = MAIN_REPLACEMENT
    book_path = os.path.join(_HERE, "kagfarm", "opening_book_elite.json")
    if os.path.exists(book_path):
        with open(book_path) as fh:
            book_src = fh.read()
        if "'''" in book_src or "\\" in book_src:
            raise SystemExit("bundle.py: elite book contains triple quotes or backslashes "
                             "-- the raw-string embedding is unsafe; change the mechanism.")
        replacement += ("\n\n# -- elite opening book (embedded for the single-file build) ----------------------\n"
                        "# The package build reads kagfarm/opening_book_elite.json from its own directory;\n"
                        "# this flattened file embeds it verbatim so both builds play the same agent.\n"
                        "_elite_book_embedded = json.loads(r'''" + book_src + "''')\n")
    parts.append(main_src.replace(MAIN_IMPORT_BLOCK, replacement).split('"""', 2)[2]
                 .strip("\n") + "\n")
    return "\n".join(parts)


def verify(src, seeds, opps):
    """Play the bundle and the package build over the same panel; require identical banks.

    Identical, not merely close: both builds are deterministic given a seed, so any difference at
    all means the flattening changed behaviour, and "close" would hide exactly the failure this
    function exists to catch.

    The bundle is imported under a throwaway name from a temporary directory rather than as
    `submission/main.py`, and that is not tidiness. `eval.evaluate` reaches the package build by
    importing the module named `main`; putting `submission/` on `sys.path` would make that name
    resolve to the bundle in both halves of the comparison, and the check would pass by comparing
    the bundle against itself. A verification that cannot fail is worse than none, because it is
    believed.

    `eval.run_one` imports the agent module by name inside a pool worker. `sys.path` propagates to
    workers under both start methods -- inherited across `fork`, copied in the preparation data
    under `spawn` -- so the temporary directory is visible to them, and the bundle is exercised
    through the same import path the harness uses.
    """
    import shutil
    import tempfile

    from eval import evaluate

    name = "_kagbundle_check"
    tmp = tempfile.mkdtemp(prefix="kagbundle-")
    try:
        with open(os.path.join(tmp, name + ".py"), "w") as fh:
            fh.write(src)
        sys.path.insert(0, tmp)
        try:
            pkg = {(r["seed"], r["opp"]): r for r in evaluate(seeds, opps, quiet=True)}
            one = {(r["seed"], r["opp"]): r
                   for r in evaluate(seeds, opps, agent_mod=name, quiet=True)}
        finally:
            if tmp in sys.path:
                sys.path.remove(tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    bad = [k for k in sorted(pkg) if pkg[k]["bank"] != one.get(k, {}).get("bank")]
    errs = [(k, one[k]["err"]) for k in sorted(one) if one[k]["err"]]
    over = [k for k in sorted(one) if one[k]["over_budget"]]
    n = len(pkg)
    print("verified %d episodes: %d agree, %d differ, %d errored, %d over budget"
          % (n, n - len(bad), len(bad), len(errs), len(over)))
    for k in bad[:5]:
        print("  seed %s vs %-9s package $%.0f, bundle $%.0f"
              % (k[0], k[1], pkg[k]["bank"], one.get(k, {}).get("bank", float("nan"))))
    for k, e in errs[:5]:
        print("  seed %s vs %-9s raised %s" % (k[0], k[1], e))
    print("  bundle worst turn %.1fms against the 1000ms actTimeout"
          % max([r["worst_ms"] for r in one.values()] or [0.0]))
    return not bad and not errs and not over


def main_cli():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default="submission/main.py")
    ap.add_argument("--seeds", type=int, default=4,
                    help="seeds to verify the flattened build over; 0 to skip verification")
    ap.add_argument("--opps", default="starter,heuristic")
    a = ap.parse_args()

    src = build()
    # Compile before writing. A syntax error would otherwise surface as an identical `err` on
    # every episode of the verification, which reports that something is wrong without saying
    # where; `compile` names the line.
    compile(src, a.out, "exec")
    path = os.path.join(_HERE, a.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(src)
    print("wrote %s (%d lines, %.0f KB)"
          % (a.out, src.count("\n") + 1, len(src.encode()) / 1024.0))

    if not a.seeds:
        print("verification skipped -- do not submit this file unverified")
        return
    ok = verify(src, range(a.seeds), a.opps.split(","))
    print("BUNDLE OK -- plays identically to the package build" if ok else
          "BUNDLE MISMATCH -- submit the package build, not this file")
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main_cli()
